name: 'Chores'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked as `stale` due to inactivity. Remove the `stale` label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This pr has been marked as `stale` due to inactivity. Remove `stale` label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          days-before-pr-close: -1
